=== JulianHurst/XMLTP/XML-TP8/TP8 - XSLT 1.0/dictionnaire.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 (x64) (http://www.altova.com) by Philippe Ramadour (UPCAM - FEA) -->
<xs:schema xmlns="http://www.univ-amu.fr/XML/dictionnaire" xmlns:dico="http://www.univ-amu.fr/XML/dictionnaire" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.univ-amu.fr/XML/dictionnaire" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="dictionnaire">
		<xs:annotation>
			<xs:documentation>Dictionnaire encyclopédique multilingue</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="false">
			<xs:sequence>
				<xs:element name="entrée" maxOccurs="unbounded">
					<xs:complexType mixed="false">
						<xs:sequence>
							<xs:element name="orthographe">
								<xs:complexType mixed="false">
									<xs:sequence>
										<xs:element name="usuelle" type="xs:string"/>
										<xs:element name="dérivée" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="type">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="verbe transitif"/>
										<xs:enumeration value="verbe intransitif"/>
										<xs:enumeration value="nom commun"/>
										<xs:enumeration value="nom propre"/>
										<xs:enumeration value="adjectif"/>
										<xs:enumeration value="pronom personnel"/>
										<xs:enumeration value="pronom relatif"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="genre" minOccurs="0">
								<xs:complexType mixed="false">
									<xs:sequence>
										<xs:element ref="dico:annotation" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="valeur" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="masculin"/>
												<xs:enumeration value="féminin"/>
												<xs:enumeration value="neutre"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="nombre" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="dico:annotation" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="valeur" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="singulier"/>
												<xs:enumeration value="pluriel"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="groupe" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="1er"/>
										<xs:enumeration value="2ème"/>
										<xs:enumeration value="3ème"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="forme" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="transitif"/>
										<xs:enumeration value="intransitif"/>
										<xs:enumeration value="réfléchi"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="prononciation" type="xs:string"/>
							<xs:choice>
								<xs:element ref="dico:renvoi"/>
								<xs:element name="significationEntrée" type="dico:significationEntréeType" maxOccurs="unbounded"/>
							</xs:choice>
							<xs:element name="significationExpression" type="dico:significationExpressionType" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="étymologie" type="xs:string" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="orthographeUnique">
						<xs:selector xpath="./dico:orthographe/dico:*"/>
						<xs:field xpath="."/>
					</xs:unique>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="entreeKey">
			<xs:selector xpath=".//dico:entrée"/>
			<xs:field xpath="./dico:orthographe/dico:usuelle"/>
		</xs:unique>
		<xs:keyref name="renvoiKeyref" refer="entreeKey">
			<xs:selector xpath=".//dico:renvoi"/>
			<xs:field xpath="."/>
		</xs:keyref>
	</xs:element>
	<xs:element name="annotation" type="xs:string"/>
	<xs:element name="renvoi" type="xs:string"/>
	<xs:complexType name="significationEntréeType">
		<xs:sequence>
			<xs:element name="domaine">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="langage familier"/>
						<xs:enumeration value="langage courant"/>
						<xs:enumeration value="finance"/>
						<xs:enumeration value="informatique"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="sens">
				<xs:complexType mixed="true">
					<xs:sequence>
						<xs:element ref="dico:renvoi" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="exemple" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="traduction" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="langue">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="anglais"/>
									<xs:enumeration value="américain"/>
									<xs:enumeration value="espagnol"/>
									<xs:enumeration value="italien"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="écriture" type="xs:string"/>
						<xs:element name="prononciation" type="xs:string"/>
						<xs:element ref="dico:annotation" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="significationExpressionType">
		<xs:complexContent>
			<xs:extension base="significationEntréeType">
				<xs:sequence>
					<xs:element name="expression" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== JulianHurst/XMLTP/XML-TP8/TP8 - XSLT 1.0/dictionnaire.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionnaire xmlns="http://www.univ-amu.fr/XML/dictionnaire" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.univ-amu.fr/XML/dictionnaire ./dictionnaire.xsd">
	<entrée>
		<orthographe>
			<usuelle>StringO1.1</usuelle>
			<dérivée>StringO1.2</dérivée>
			<dérivée>StringO1.3</dérivée>
		</orthographe>
		<type>nom commun</type>
		<genre valeur="féminin"/>
		<nombre valeur="pluriel">
			<annotation>Toujours pluriel</annotation>
			<annotation>Vraiment toujours pluriel :-)</annotation>
		</nombre>
		<prononciation>StringP1.1</prononciation>
		<significationEntrée>
			<domaine>langage courant</domaine>
			<sens>bla bla bla
				<renvoi>StringO1.1</renvoi>
				<renvoi>StringO2.1</renvoi>
			</sens>
		</significationEntrée>
		<significationEntrée>
			<domaine>langage familier</domaine>
			<sens>bla bla</sens>
			<exemple>StringE1.1</exemple>
			<traduction>
				<langue>italien</langue>
				<écriture>StringT1.1</écriture>
				<prononciation>StringP1.1</prononciation>
				<annotation>Annotation1</annotation>
				<annotation>Annotation2</annotation>
			</traduction>
			<traduction>
				<langue>américain</langue>
				<écriture>StringT1.2</écriture>
				<prononciation>StringP1.2</prononciation>
			</traduction>
		</significationEntrée>
		<étymologie>StringE1.1</étymologie>
	</entrée>
	<entrée>
		<orthographe>
			<usuelle>StringO2.1</usuelle>
			<dérivée>StringO2.2</dérivée>
		</orthographe>
		<type>pronom personnel</type>
		<genre valeur="masculin"/>
		<nombre valeur="singulier"/>
		<prononciation>StringP2.1</prononciation>
		<significationEntrée>
			<domaine>informatique</domaine>
			<sens>StringS2.1</sens>
			<exemple>StringE2.1</exemple>
			<exemple>StringE2.2</exemple>
		</significationEntrée>
		<significationExpression>
			<domaine>informatique</domaine>
			<sens>StringS2.1</sens>
			<traduction>
				<langue>italien</langue>
				<écriture>StringE2.1</écriture>
				<prononciation>StringP2.1</prononciation>
			</traduction>
			<expression>StringE2.1</expression>
		</significationExpression>
		<étymologie>StringE2.1</étymologie>
	</entrée>
	<entrée>
		<orthographe>
			<usuelle>StringO3.1</usuelle>
			<dérivée>StringO3.2</dérivée>
		</orthographe>
		<type>nom commun</type>
		<genre valeur="neutre"/>
		<nombre valeur="singulier"/>
		<groupe>2ème</groupe>
		<forme>réfléchi</forme>
		<prononciation>StringP1.1</prononciation>
		<renvoi>StringO2.1</renvoi>
	</entrée>
</dictionnaire>
