=== JulianHurst/XMLTP/XML-TP8/TP8 - XSLT 1.0/guide.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 (x64) (http://www.altova.com) by Philippe Ramadour (UPCAM - FEA) -->
<xs:schema xmlns="http://www.univ-amu.fr/XML/guide" xmlns:gui="http://www.univ-amu.fr/XML/guide" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:com="http://www.univ-amu.fr/XML/commun" targetNamespace="http://www.univ-amu.fr/XML/guide" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://www.univ-amu.fr/XML/commun" schemaLocation="commun.xsd"/>
	<xs:element name="guide">
		<xs:annotation>
			<xs:documentation>Guide d'itinéraires à ski</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="false">
			<xs:sequence>
				<xs:element name="titre" type="xs:string"/>
				<xs:element name="auteur" type="com:personneType" maxOccurs="unbounded"/>
				<xs:element name="éditeur" type="xs:string"/>
				<xs:element name="année" type="xs:gYear"/>
				<xs:element name="vallon" maxOccurs="unbounded">
					<xs:complexType mixed="false">
						<xs:sequence>
							<xs:element name="nom" type="xs:string"/>
							<xs:element name="introduction">
								<xs:complexType mixed="false">
									<xs:sequence>
										<xs:element ref="gui:paragraphe" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
								<xs:unique name="noteDansIntroductionVallonUnique">
									<xs:selector xpath=".//gui:note"/>
									<xs:field xpath="./@type"/>
									<xs:field xpath="."/>
								</xs:unique>
							</xs:element>
							<xs:element name="itinéraire" maxOccurs="unbounded">
								<xs:complexType mixed="false">
									<xs:sequence>
										<xs:element name="nom" type="xs:string"/>
										<xs:element name="altitude">
											<xs:simpleType>
												<xs:restriction base="xs:positiveInteger">
													<xs:maxExclusive value="9000"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="cotation">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="\*{1,5}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element ref="gui:paragraphe" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="numéro" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="I\d{6}"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
								<xs:unique name="noteDansItineraireUnique">
									<xs:selector xpath=".//gui:note"/>
									<xs:field xpath="./@type"/>
									<xs:field xpath="."/>
								</xs:unique>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="vallonUnique">
			<xs:selector xpath=".//gui:vallon"/>
			<xs:field xpath="./gui:nom"/>
		</xs:unique>
		<xs:unique name="itinéraireNuméroUnique">
			<xs:selector xpath=".//gui:itinéraire"/>
			<xs:field xpath="./@numéro"/>
		</xs:unique>
		<xs:unique name="itinéraireNomUnique">
			<xs:selector xpath=".//gui:itinéraire"/>
			<xs:field xpath="./gui:nom"/>
		</xs:unique>
		<xs:unique name="noteDansGuideUnique">
			<xs:selector xpath=".//gui:note"/>
			<xs:field xpath="./@ident"/>
		</xs:unique>
		<xs:key name="itinéraireEtNoteKey">
			<xs:selector xpath=".//gui:itinéraire|.//gui:note"/>
			<xs:field xpath="./@numéro|./@ident"/>
		</xs:key>
		<xs:keyref name="renvoiKeyref" refer="gui:itinéraireEtNoteKey">
			<xs:annotation>
				<xs:documentation>Pour la contrainte portant sur les renvois, il faut que les types des numéros des itinéraires, des identifiants des notes et des cibles des renvois soient compatibles. Pour ce faire, on peut soit ne pas toucher au type demandé pour le numéro d'un itinéraire et baser les 2 autres données sur des types numériques entiers positifs. On peut aussi choisir une autre solution : ici, l'identifiant d'un itinéraire est une chaîne basée sur un motif commançant par un 'I' suivi de 6 chiffres, l'identifiant d'une note est une chaîne basée sur un motif commençant par un 'N' suivi de 6 chiffres et, enfin, la cible d'un renvoi est une chaîne basée sur l'un ou l'autre de ces 2 motifs.</xs:documentation>
			</xs:annotation>
			<xs:selector xpath=".//gui:renvoi"/>
			<xs:field xpath="./@cible"/>
		</xs:keyref>
	</xs:element>
	<xs:element name="paragraphe">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="renvoi">
					<xs:complexType mixed="false">
						<xs:attribute name="cible" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="I\d{6}"/>
									<xs:pattern value="N\d{6}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="note">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="ident">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:pattern value="N\d{6}"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="type">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="prudence"/>
											<xs:enumeration value="matériel"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JulianHurst/XMLTP/XML-TP8/TP8 - XSLT 1.0/guide.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="file:///C:/Users/h12026079/Desktop/XML/TP8%20-%20XSLT%201.0/guide.xslt"?>
<guide xmlns="http://www.univ-amu.fr/XML/guide" xmlns:com="http://www.univ-amu.fr/XML/commun" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.univ-amu.fr/XML/guide ./guide.xsd">
	<titre>Guide d'itinéraires à ski</titre>
	<auteur>
		<com:civilité>M.</com:civilité>
		<com:prénomUsuel>Premier</com:prénomUsuel>
		<com:nom>Auteur</com:nom>
	</auteur>
	<auteur>
		<com:civilité>M.</com:civilité>
		<com:prénomUsuel>Second</com:prénomUsuel>
		<com:nom>Auteur</com:nom>
	</auteur>
	<éditeur>Editeur</éditeur>
	<année>2000</année>
	<vallon>
		<nom>Vallon1</nom>
		<introduction>
			<paragraphe>
				Premier paragraphe de l'introduction du premier vallon
				<renvoi cible="I000001"/>
				<note type="prudence" ident="N000001">Une note de type prudence</note>
			</paragraphe>
			<paragraphe>
				Second paragraphe de l'introduction du premier vallon
				<renvoi cible="N000001"/>
				<note type="prudence" ident="N000002">Une autre note de type prudence</note>
			</paragraphe>
		</introduction>
		<itinéraire numéro="I000001">
			<nom>Itineraire1</nom>
			<altitude>7500</altitude>
			<cotation>**</cotation>
			<paragraphe>
				Premier paragraphe du premier itinéraire du premier vallon
				<renvoi cible="N000002"/>
				<note type="matériel" ident="N000003">Une note de type matériel</note>
			</paragraphe>
			<paragraphe>
				Second paragraphe du premier itinéraire du premier vallon
				<note type="prudence" ident="N000004">Une note de type prudence</note>
				<note type="matériel" ident="N000005">Une autre note de type matériel</note>
			</paragraphe>
		</itinéraire>
		<itinéraire numéro="I000002">
			<nom>Itineraire2</nom>
			<altitude>8123</altitude>
			<cotation>***</cotation>
			<paragraphe>
				Premier paragraphe du second itinéraire du premier vallon
				<renvoi cible="N000005"/>
				<note type="prudence" ident="N000006">Une note de type prudence</note>
			</paragraphe>
			<paragraphe>
				Second paragraphe du second itinéraire du second vallon
			</paragraphe>
		</itinéraire>
	</vallon>
	<vallon>
		<nom>Vallon2</nom>
		<introduction>
			<paragraphe>
				Premier paragraphe de l'introduction du second vallon
				<renvoi cible="I000002"/>
			</paragraphe>
			<paragraphe>
				Second paragraphe de l'introduction du second vallon
				<renvoi cible="I000002"/>
				<note type="matériel" ident="N000007">Une note de type matériel</note>
			</paragraphe>
		</introduction>
		<itinéraire numéro="I000003">
			<nom>Itineraire3</nom>
			<altitude>6389</altitude>
			<cotation>*</cotation>
			<paragraphe>
				Premier paragraphe du premier itinéraire du second vallon
				<renvoi cible="I000001"/>
				<note type="prudence" ident="N000008">Une note de type prudence</note>
			</paragraphe>
			<paragraphe>
				Second paragraphe du premier itinéraire du second vallon
			</paragraphe>
		</itinéraire>
		<itinéraire numéro="I000005">
			<nom>Itineraire4</nom>
			<altitude>6388</altitude>
			<cotation>****</cotation>
			<paragraphe>
				Premier paragraphe du second itinéraire du second vallon
				<renvoi cible="I000002"/>
				<note type="prudence" ident="N000009">Une note de type prudence</note>
			</paragraphe>
			<paragraphe>
				Second paragraphe du second itinéraire du second vallon
				<renvoi cible="N000003"/>
				<note type="matériel" ident="N000000">Une note de type matériel</note>
			</paragraphe>
		</itinéraire>
	</vallon>
</guide>
