=== JulianHurst/XMLTP/XML-TP8/TP8 - XSLT 1.0/livre.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.univ-amu.fr/XML/livre" xmlns:liv="http://www.univ-amu.fr/XML/livre" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:com="http://www.univ-amu.fr/XML/commun" targetNamespace="http://www.univ-amu.fr/XML/livre" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://www.univ-amu.fr/XML/commun" schemaLocation="commun.xsd"/>
	<xs:element name="livre">
		<xs:annotation>
			<xs:documentation>Livre à contenu pédagogique</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="false">
			<xs:sequence>
				<xs:element name="titre" type="xs:string"/>
				<xs:element name="auteur" type="com:personneType" maxOccurs="unbounded"/>
				<xs:element name="éditeur" type="xs:string"/>
				<xs:element name="année" type="xs:gYear"/>
				<xs:element name="leçon" maxOccurs="unbounded">
					<xs:complexType mixed="false">
						<xs:sequence>
							<xs:element name="titre" type="xs:string"/>
							<xs:element ref="liv:introduction"/>
							<xs:element name="chapitre" maxOccurs="unbounded">
								<xs:complexType mixed="false">
									<xs:sequence>
										<xs:element name="titre" type="xs:string"/>
										<xs:element ref="liv:introduction"/>
										<xs:element name="section" maxOccurs="unbounded">
											<xs:complexType mixed="false">
												<xs:sequence>
													<xs:element name="titre" type="xs:string"/>
													<xs:element ref="liv:paragraphe" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
								<xs:unique name="titreSectionUnique">
									<xs:selector xpath="./liv:section"/>
									<xs:field xpath="./liv:titre"/>
								</xs:unique>
							</xs:element>
							<xs:element name="exercices">
								<xs:complexType mixed="false">
									<xs:sequence>
										<xs:element name="exercice" maxOccurs="unbounded">
											<xs:complexType mixed="false">
												<xs:sequence>
													<xs:element name="QCM">
														<xs:complexType mixed="false">
															<xs:sequence>
																<xs:element name="énoncé" type="xs:string"/>
																<xs:element name="proposition" minOccurs="2" maxOccurs="unbounded">
																	<xs:complexType mixed="false">
																		<xs:simpleContent>
																			<xs:extension base="xs:string">
																				<xs:attribute name="numéro" type="xs:positiveInteger" use="required"/>
																			</xs:extension>
																		</xs:simpleContent>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="corrigé">
														<xs:complexType mixed="false">
															<xs:sequence>
																<xs:element name="bonneProposition" maxOccurs="unbounded">
																	<xs:complexType mixed="false">
																		<xs:attribute name="numéro" type="xs:positiveInteger" use="required"/>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="numéro" type="xs:positiveInteger" use="required"/>
											</xs:complexType>
											<xs:key name="numéroPropositionKey">
												<xs:selector xpath=".//liv:proposition"/>
												<xs:field xpath="./@numéro"/>
											</xs:key>
											<xs:unique name="numéroBonnePropositionUnique">
												<xs:selector xpath=".//liv:bonneProposition"/>
												<xs:field xpath="./@numéro"/>
											</xs:unique>
											<xs:keyref name="numéroBonnePropositionKeyref" refer="numéroPropositionKey">
												<xs:selector xpath=".//liv:bonneProposition"/>
												<xs:field xpath="./@numéro"/>
											</xs:keyref>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="numéro" type="xs:positiveInteger" use="required"/>
					</xs:complexType>
					<xs:unique name="titreChapitreUnique">
						<xs:selector xpath="./liv:chapitre"/>
						<xs:field xpath="./liv:titre"/>
					</xs:unique>
					<xs:unique name="numéroExerciceUnique">
						<xs:selector xpath=".//liv:exercice"/>
						<xs:field xpath="./@numéro"/>
					</xs:unique>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="ISBN" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:positiveInteger">
						<xs:totalDigits value="13"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
		<xs:unique name="numéroLeçonUnique">
			<xs:selector xpath=".//liv:leçon"/>
			<xs:field xpath="./@numéro"/>
		</xs:unique>
		<xs:unique name="titreLeçonUnique">
			<xs:selector xpath=".//liv:leçon"/>
			<xs:field xpath="./liv:titre"/>
		</xs:unique>
		<xs:unique name="auteurUnique">
			<xs:selector xpath=".//liv:auteur"/>
			<xs:field xpath="./com:nom"/>
			<xs:field xpath="./com:prénomUsuel"/>
		</xs:unique>
		<xs:key name="leçonKey">
			<xs:selector xpath=".//liv:leçon"/>
			<xs:field xpath="./@numéro"/>
			<xs:field xpath="./liv:titre"/>
		</xs:key>
		<xs:keyref name="renvoiKeyref" refer="leçonKey">
			<xs:selector xpath=".//liv:renvoi"/>
			<xs:field xpath="./@numéro"/>
			<xs:field xpath="./@titre"/>
		</xs:keyref>
	</xs:element>
	<xs:element name="paragraphe">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="renvoi" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="titre" type="xs:string" use="required"/>
						<xs:attribute name="numéro" type="xs:positiveInteger" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="introduction">
		<xs:complexType mixed="false">
			<xs:sequence>
				<xs:element ref="liv:paragraphe" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JulianHurst/XMLTP/XML-TP8/TP8 - XSLT 1.0/livre.xml
<?xml version="1.0" encoding="UTF-8"?>
<liv:livre ISBN="1234567891234" xsi:schemaLocation="http://www.univ-amu.fr/XML/livre livre.xsd" xmlns:liv="http://www.univ-amu.fr/XML/livre" xmlns:com="http://www.univ-amu.fr/XML/commun" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<liv:titre>String</liv:titre>
	<liv:auteur>
		<com:civilité>M.</com:civilité>
		<com:prénomUsuel>String</com:prénomUsuel>
		<com:nom>String</com:nom>
	</liv:auteur>
	<liv:auteur>
		<com:civilité>Mlle</com:civilité>
		<com:prénomUsuel>String</com:prénomUsuel>
		<com:nom>String2</com:nom>
	</liv:auteur>
	<liv:éditeur>String</liv:éditeur>
	<liv:année>2000</liv:année>
	<liv:leçon numéro="1">
		<liv:titre>Leçon 1</liv:titre>
		<liv:introduction>
			<liv:paragraphe>
				blabla <liv:renvoi numéro="2" titre="Leçon 2"/> blabla
			</liv:paragraphe>
		</liv:introduction>
		<liv:chapitre>
			<liv:titre>Chapitre 1</liv:titre>
			<liv:introduction>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="2" titre="Leçon 2"/> blabla
				</liv:paragraphe>
			</liv:introduction>
			<liv:section>
				<liv:titre>Section 1</liv:titre>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="2" titre="Leçon 2"/> blabla
				</liv:paragraphe>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="1" titre="Leçon 1"/> blabla
				</liv:paragraphe>
			</liv:section>
			<liv:section>
				<liv:titre>Section 2</liv:titre>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="1" titre="Leçon 1"/> blabla
				</liv:paragraphe>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="2" titre="Leçon 2"/> blabla
				</liv:paragraphe>
			</liv:section>
		</liv:chapitre>
		<liv:chapitre>
			<liv:titre>Chapitre 2</liv:titre>
			<liv:introduction>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="2" titre="Leçon 2"/> blabla
				</liv:paragraphe>
			</liv:introduction>
			<liv:section>
				<liv:titre>Section 1</liv:titre>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="2" titre="Leçon 2"/> blabla
				</liv:paragraphe>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="2" titre="Leçon 2"/> blabla
				</liv:paragraphe>
			</liv:section>
			<liv:section>
				<liv:titre>Section 2</liv:titre>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="2" titre="Leçon 2"/> blabla
				</liv:paragraphe>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="1" titre="Leçon 1"/> blabla
				</liv:paragraphe>
			</liv:section>
		</liv:chapitre>
		<liv:exercices>
			<liv:exercice numéro="1">
				<liv:QCM>
					<liv:énoncé>String</liv:énoncé>
					<liv:proposition numéro="1">Réponse 1</liv:proposition>
					<liv:proposition numéro="2">Réponse 2</liv:proposition>
				</liv:QCM>
				<liv:corrigé>
					<liv:bonneProposition numéro="1"/>
				</liv:corrigé>
			</liv:exercice>
			<liv:exercice numéro="2">
				<liv:QCM>
					<liv:énoncé>String</liv:énoncé>
					<liv:proposition numéro="1">Réponse 1</liv:proposition>
					<liv:proposition numéro="2">Réponse 2</liv:proposition>
				</liv:QCM>
				<liv:corrigé>
					<liv:bonneProposition numéro="1"/>
					<liv:bonneProposition numéro="2"/>
				</liv:corrigé>
			</liv:exercice>
		</liv:exercices>
	</liv:leçon>
	<liv:leçon numéro="2">
		<liv:titre>Leçon 2</liv:titre>
		<liv:introduction>
			<liv:paragraphe>
				blabla <liv:renvoi numéro="1" titre="Leçon 1"/> blabla
			</liv:paragraphe>
		</liv:introduction>
		<liv:chapitre>
			<liv:titre>Chapitre 1</liv:titre>
			<liv:introduction>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="1" titre="Leçon 1"/> blabla
				</liv:paragraphe>
			</liv:introduction>
			<liv:section>
				<liv:titre>Section 1</liv:titre>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="1" titre="Leçon 1"/> blabla
				</liv:paragraphe>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="2" titre="Leçon 2"/> blabla
				</liv:paragraphe>
			</liv:section>
			<liv:section>
				<liv:titre>Section 2</liv:titre>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="1" titre="Leçon 1"/> blabla
				</liv:paragraphe>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="1" titre="Leçon 1"/> blabla
				</liv:paragraphe>
			</liv:section>
		</liv:chapitre>
		<liv:chapitre>
			<liv:titre>Chapitre 2</liv:titre>
			<liv:introduction>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="1" titre="Leçon 1"/> blabla
				</liv:paragraphe>
			</liv:introduction>
			<liv:section>
				<liv:titre>Section 1</liv:titre>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="1" titre="Leçon 1"/> blabla
				</liv:paragraphe>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="1" titre="Leçon 1"/> blabla
				</liv:paragraphe>
			</liv:section>
			<liv:section>
				<liv:titre>Section 2</liv:titre>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="1" titre="Leçon 1"/> blabla
				</liv:paragraphe>
				<liv:paragraphe>
					blabla <liv:renvoi numéro="1" titre="Leçon 1"/> blabla
				</liv:paragraphe>
			</liv:section>
		</liv:chapitre>
		<liv:exercices>
			<liv:exercice numéro="1">
				<liv:QCM>
					<liv:énoncé>String</liv:énoncé>
					<liv:proposition numéro="1">Réponse 1</liv:proposition>
					<liv:proposition numéro="2">Réponse 2</liv:proposition>
					<liv:proposition numéro="3">Réponse 3</liv:proposition>
				</liv:QCM>
				<liv:corrigé>
					<liv:bonneProposition numéro="1"/>
					<liv:bonneProposition numéro="3"/>
				</liv:corrigé>
			</liv:exercice>
			<liv:exercice numéro="2">
				<liv:QCM>
					<liv:énoncé>String</liv:énoncé>
					<liv:proposition numéro="1">Réponse 1</liv:proposition>
					<liv:proposition numéro="2">Réponse 2</liv:proposition>
				</liv:QCM>
				<liv:corrigé>
					<liv:bonneProposition numéro="2"/>
				</liv:corrigé>
			</liv:exercice>
		</liv:exercices>
	</liv:leçon>
</liv:livre>
